services:
  postgres:
    image: postgres:15.3
    ports:
      - ${DATABASE_PORT}:5432 # expose port 5432
    environment:
      POSTGRES_USER: ${DATABASE_USERNAME}
      POSTGRES_PASSWORD: ${DATABASE_PASSWORD}
      POSTGRES_DB: ${DATABASE_NAME}
    volumes:
      - ./.data/db:/var/lib/postgresql/data # mount the postgres data folder