import "@/app/globals.css";
import StyledJsxRegistry from "@/app/registry";

export const metadata = {
  title: "Skripsi App",
  description: "Generated by agungrhiz",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className="m-0">
        <StyledJsxRegistry>
          {children}
        </StyledJsxRegistry>
      </body>
    </html>
  );
}
