import "@/app/globals.css";
import { Inter } from "next/font/google";
import StyledJsxRegistry from "@/app/registry";
import AnimationLayout from "@/components/organisms/animation-layout";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Skripsi App",
  description: "Generated by agungrhiz",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <StyledJsxRegistry>
          <AnimationLayout>{children}</AnimationLayout>
        </StyledJsxRegistry>
      </body>
    </html>
  );
}
